<?php

$labels = [];
$labels['filters'] = 'Reguły filtrowania';
$labels['storedfilters'] = 'Utworzone reguły filtrowania';
$labels['whatfilter'] = 'Jakie pole ma być filtrowane?';
$labels['searchstring'] = 'Zawiera';
$labels['movefrom'] = 'Sprawdzaj w';
$labels['moveto'] = 'Przenoś do';
$labels['from'] = 'Pole "Od"';
$labels['to'] = 'Pole "Do:';
$labels['cc'] = 'Pole "CC"';
$labels['subject'] = 'Tytuł wiadomości';
$labels['delete'] = 'Usuń';
$labels['filterpriority'] = 'Nie korzystaj z pozostałych reguł';

$messages = [];
$messages['nosearchstring'] = "Pole 'Zawiera' nie może być puste.";
$messages['successfullysaved'] = "Reguła filtrowania zapisana.";
$messages['unsuccessfullysaved'] = "Wystąpił błąd. Nie udało się zapisać reguły filtrowania.";
$messages['successfullydeleted'] = "Reguła filtrowania została usunięta.";
$messages['unsuccessfullydeleted'] = "Wystąpił błąd. Nie udało się usunąć reguły filtrowania.";
$messages['msg_if_field'] = 'Jeśli pole';
$messages['msg_contains'] = 'zawiera';
$messages['msg_move_msg_in'] = 'przenieś wiadomość do';
$messages['msg_move_msg_from'] = 'od';
$messages['msg_no_stored_filters'] = "Nie ma żadnych reguł filtrowania wiadomości";
